### ISSUE TITLE
[Bug]: Header Tabs Keep Resetting On Reload

### ISSUE THREAD

**Issue by Neverdusk** [anapnoe/stable-diffusion-webui-ux#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I recently made a fresh install of SDUX and everything is working great - except that every time I reload the UI (including from the settings or extensions page), my Header Tabs keep getting reset. In settings, they'll all appear off. 
![Screenshot 2023-06-02 102250](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/3ce9f0e8-877b-47c2-a14b-0912dc605cce)
However, if I select the same settings and then click save, the UI claims that nothing was updated. But if I make something different, it updates. In other words - the settings are already saved and the UI recognizes they're the same, but whenever it loads it seems to skip this particular setting. 
![Screenshot 2023-06-02 102448](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/21ad9dd4-59b6-4bb9-8810-f1b6b1919665)

I'm not really sure what started this, but it's been a bit inconvenient since I use header tabs a lot. 

### Steps to reproduce the problem

1. Go to Settings
2. Save Header Tabs
3. Reload UI
4. UI Reloads Without Headers

### What should have happened?

1. Go to Settings
2. Save Header Tabs
3. Reload UI
4. Head Tabs Are Saved and Appear the Same

### Commit where the problem happens

V1.3.0-264-g9931e861

### What Python version are you running on ?

Python 3.10.x

### What device are you running WebUI on?

Nvidia GPUs (RTX 20 above)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --no-half-vae --api --autolaunch
```

### List of extensions

Stable-Diffusion-Webui-Civitai-Helper | https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git | main | 920ca326 | Tue May 23 11:53:22 2023
a1111-sd-webui-lycoris | https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git | main | b0d24ca6 | Wed May 17 00:19:32 2023
multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111 | main | 70b3c5ea | Sun May 28 09:11:28 2023
sd-dynamic-prompts | https://github.com/adieyal/sd-dynamic-prompts.git | main | d34bdc17 | Thu Jun 1 07:53:09 2023
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | main | 4f0f26b7 | Thu Jun 1 15:38:57 2023
sd-webui-cutoff | https://github.com/hnmr293/sd-webui-cutoff | main | 3a073e9c | Wed May 3 07:14:40 2023
sd-webui-lora-block-weight | https://github.com/hako-mikan/sd-webui-lora-block-weight.git | main | 19a5dd07 | Wed May 31 17:11:13 2023
sd-webui-photopea-embed | https://github.com/yankooliveira/sd-webui-photopea-embed | main | f465a26a | Sat May 13 18:09:09 2023
sd-webui-segment-anything | https://github.com/continue-revolution/sd-webui-segment-anything | master | 0c2d2b78 | Thu Jun 1 19:35:41 2023
sdweb-merge-block-weighted-gui | https://github.com/bbc-mc/sdweb-merge-block-weighted-gui.git | master | 8a62a753 | Thu Jan 19 21:31:06 2023
stable-diffusion-webui-Layer-Divider | https://github.com/jhj0517/stable-diffusion-webui-Layer-Divider | master | 15645066 | Thu May 11 13:02:40 2023
ultimate-upscale-for-automatic1111 | https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git | master | 756bb505 | Fri May 5 00:22:21 2023

### Console logs

```Shell
venv "C:\Users\silve\Documents\AI Art\__SDUX\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.3.0-264-g9931e861
Commit hash: 9931e861dfb128735c4a928a7beb5b5c0af30593
Installing requirements
Requirement already satisfied: send2trash~=1.8 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (1.8.2)
Requirement already satisfied: dynamicprompts[attentiongrabber,magicprompt]~=0.27.0 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (0.27.0)
Requirement already satisfied: pyparsing~=3.0 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.0.9)
Requirement already satisfied: jinja2~=3.1 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1.2)
Requirement already satisfied: transformers[torch]~=4.19 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (4.25.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from jinja2~=3.1->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.1.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2023.5.5)
Requirement already satisfied: huggingface-hub<1.0,>=0.10.0 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.15.1)
Requirement already satisfied: packaging>=20.0 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (23.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (6.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (4.65.0)
Requirement already satisfied: filelock in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.12.0)
Requirement already satisfied: numpy>=1.17 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.23.5)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.13.3)
Requirement already satisfied: requests in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.31.0)
Requirement already satisfied: torch!=1.12.0,>=1.7 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.0.1+cu118)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from huggingface-hub<1.0,>=0.10.0->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (4.6.2)
Requirement already satisfied: fsspec in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from huggingface-hub<1.0,>=0.10.0->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2023.5.0)
Requirement already satisfied: sympy in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.12)
Requirement already satisfied: networkx in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1)
Requirement already satisfied: colorama in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from tqdm>=4.27->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.4.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2023.5.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.26.16)
Requirement already satisfied: mpmath>=0.19 in c:\users\silve\documents\ai art\__sdux\venv\lib\site-packages (from sympy->torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.3.0)
sd-dynamic-prompts installer: running 'C:\Users\silve\Documents\AI Art\__SDUX\venv\Scripts\python.exe' -m pip install 'send2trash~=1.8' 'dynamicprompts[attentiongrabber,magicprompt]~=0.27.0'



Launching Web UI with arguments: --xformers --no-half-vae --api --autolaunch
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: C:\Users\silve\Documents\AI Art\__SDUX\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
ControlNet v1.1.208
ControlNet v1.1.208
Installing Layer Divider Extension: Installing  segment-anything
Installing Layer Divider Extension: Installing  opencv-python
Installing Layer Divider Extension: Installing  pytoshop==1.1.0
Checkpoint __Anime\_Custom_Test\QRB2AGHIB.safetensors [f973437a47] not found; loading fallback __Anime\_Custom\AMV.safetensors [cdd759cf8d]
Loading weights [cdd759cf8d] from C:\Users\silve\Documents\AI Art\__SDUX\models\Stable-diffusion\__Anime\_Custom\AMV.safetensors
Create LRU cache (max_size=16) for preprocessor results.
Creating model from config: C:\Users\silve\Documents\AI Art\__SDUX\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Create LRU cache (max_size=16) for preprocessor results.
Loading VAE weights specified in settings: C:\Users\silve\Documents\AI Art\__SDUX\models\VAE\AnythingV3-pruned.vae.pt
Applying optimization: xformers... done.
Textual inversion embeddings loaded(7): bad-artist, bad-artist-anime, bad-hands-5, CharTurner, CharTurner2, EasyNegative, PlanIt
Model loaded in 10.5s (load weights from disk: 0.6s, create model: 0.6s, apply weights to model: 5.3s, apply half(): 0.7s, load VAE: 0.8s, move model to device: 0.8s, load textual inversion embeddings: 1.6s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 31.1s (import torch: 4.6s, import gradio: 3.0s, import ldm: 1.3s, other imports: 3.0s, setup codeformer: 0.2s, load scripts: 7.1s, create ui: 11.1s, gradio launch: 0.4s).
Restarting UI...
Closing server running on port: 7860
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: C:\Users\silve\Documents\AI Art\__SDUX\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
ControlNet v1.1.208
Installing Layer Divider Extension: Installing  segment-anything
Installing Layer Divider Extension: Installing  opencv-python
Installing Layer Divider Extension: Installing  pytoshop==1.1.0
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 6.8s (load scripts: 5.2s, create ui: 0.9s, gradio launch: 0.6s).
Restarting UI...
Closing server running on port: 7860
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: C:\Users\silve\Documents\AI Art\__SDUX\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
ControlNet v1.1.208
Installing Layer Divider Extension: Installing  segment-anything
Installing Layer Divider Extension: Installing  opencv-python
Installing Layer Divider Extension: Installing  pytoshop==1.1.0
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 6.1s (load scripts: 4.8s, create ui: 1.0s, gradio launch: 0.1s).
```

### Additional information

Happened on a fresh install I did yesterday. I only noticed the issue today.

**Comment by anapnoe** [comment]
add the header hidden tabs to the quicksettings i need to look into this when when i have some spare time

**Comment by anapnoe** [comment]
fixed something went wrong with the previous merge

**Comment by LoathingScreen** [comment]
its not fixed for me :/

> fixed something went wrong with the previous merge

**Comment by anapnoe** [comment]
can you add the options to quicksettings and try from there?
you can add them by clicking on the menu+ button on the most right of the setting
quicksettings are shown when clicked on the right of the top header 3 dots
does the saved settings show up there i want to be sure before i reopen the issue that it affects only the setting view

**Comment by LoathingScreen** [comment]
ok, so I added the tab selector to QS and set up my tabs, reloaded UI and tabs are still not there and the setting is not in the QS menu

**Comment by anapnoe** [comment]
something is wrong with your setup please install a clean uiux with no extensions and try again i canot reproduce the issue 
you can try first place your config file to a new place on your hd and restart a new config will be created with the default settings if this doent work do a clean install on my end both s and qs are working as they should

![Untitled](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/124302297/19c11533-ccb5-48cb-9ffe-9655c80a570d)

**Comment by LoathingScreen** [comment]
> something is wrong with your setup please install a clean uiux with no extensions and try again i canot reproduce the issue you can try first place your config file to a new place on your hd and restart a new config will be created with the default settings if this doent work do a clean install on my end both s and qs are working as they should
> 
> screenshot after restart ![Untitled](https://user-images.githubusercontent.com/124302297/246632313-19c11533-ccb5-48cb-9ffe-9655c80a570d.png)

damn, I reinstalled python 3.10.6 and made a clean install, and its the same deal, I change the tabs, it says 1 setting changed 'header tabs' but when I reload the ui they are not there. I was able to manually input some tabs in the json file and they stuck but when i added more in the settings tab it said it changed as usual but when I reopen the json file, those settings remain untouched ( I keep the tabs that i manually added).

**Comment by LoathingScreen** [comment]
I run with this args if its of help
--opt-channelslast --opt-sdp-attention --ckpt-dir=D:/SD_MODELS/checkpoints --vae-dir D:/SD_MODELS/VAE --embeddings-dir D:/SD_MODELS/embeddings --lora-dir D:/SD_MODELS/lora --esrgan-models-path D:/SD_MODELS/ESRGAN --hypernetwork-dir D:/SD_MODELS/hypernetworks --textual-inversion-templates-dir D:/SD_MODELS/textual_inversion_templates --xformers --autolaunch --port xxxxx

**Comment by robonxt** [comment]
this is also broken for me, but I temporary fixed it by manually copying the values from the `config.json` to the `ui-config.json` file.
